### ISSUE TITLE
Unpublished not showing in Umbraco 8

### ISSUE THREAD

**Issue by colin-tactuum** [enkelmedia/TheDashboard#60]
I have installed the package in an Umbraco 8.15.1 and 8.16 instance of Umbraco.

The Unpublished content list is always showing 0 entries even when there are unpublished content.

I have tried this in production sites as well as fresh Umbraco sites.

**Comment by enkelmedia** [comment]
Thanks @colin-tactuum - not sure what has happened here - used to work on "older" versions.

I'll have a look

**Comment by enkelmedia** [comment]
Ahh, @colin-tactuum after looking closer at this I think I remember the idea behind this. The header and description is miss-leading, the heading should probably say something like "Pending changes" or "Unpublished Changed" not "Unpublished Content".

So the idea is that this list should show items that has a published version but also have a saved version that is not scheduled for publishing. Umbraco calls this "unpublished-version". This happens when a editor just press "Save" and forget to publish. 

I think that the assumption is that we don't need to display all content items that is unpublished as this might be a lot of content and most of them is probably intentionally unpublished by the editor.

So what I'm talking about is nodes that looks like this in the tree:

![image](https://user-images.githubusercontent.com/1782524/132513572-0d8f6b01-2422-427c-b555-aa56b49f64ab.png)

Does this make sense? We defiantly need to changed the description text to reflect this.

**Comment by colin-tactuum** [comment]
Hi @enkelmedia thanks for looking at this.

Yes, this does make sense to me.  I will convey this to my client and hope that it is sufficient as I think they are used to the way it worked in Umbraco 7 (showing all "unpublished" content).

Thanks.

**Comment by enkelmedia** [comment]
I see!

I'm not saying that we can't or should not ever show "All Unpublished Content" - it was not the intention of the feature but we could probably provide some way to show all unpublished content if this is something that people want.

I'll keep the issue open until the text-changes has been made and also to give you an opportunity to feed in any feedback from your client.

All the best!

**Comment by colin-tactuum** [comment]
Unfortunately, my client does need it to show all unpublished content as the users currently rely on it quite heavily.  I will download the source and see what I can do myself.  Thanks

**Comment by enkelmedia** [comment]
I see, the "fix" should be quite simple but I'm not sure that we should change the current feature, I think that the "bug" in that regards is the header and description - the functionality works as intended.

Maybe the list of "Unpublished Content" is it's own feature. I can how ever see one issue with this, some sites might have lots of unpublished content (we have a client with about 1000 unpublished pages) which might slow down the load of the overview.

Just a "quick and dirty" example, i think that both boxes should have a "counter" on them as well.

![image](https://user-images.githubusercontent.com/1782524/132645588-4f2830aa-a825-4e18-800a-af495856b50a.png)

**Comment by colin-tactuum** [comment]
I completely agree that everything is working as expected just now and it's just the header that needs changed to be clearer on what it shows.

Thanks for all your help.

**Comment by enkelmedia** [comment]
But if I understood you correct you do need this feature for unpublished content?

You could create your own branch but if you are open to create a PR for this it would be create! I did some research around the SQL required to fetch unpublished content and it looks something like this: 

Table: umbracoDocument


| Result              | Published | Edit |
|-------------------|---------|---------|
| Published with pending changed:             | 1     | 1      |
| Published with no pending changes:      | 1       | 0       |
| Unpublished | 0       |    0/1    |
