### ISSUE TITLE
Can't add/change labels in language files

### ISSUE THREAD

**Issue by huwred** [enkelmedia/TheDashboard#84]
I created a custom counter but am unable to add the label to the language files, everytime I build the language file gets overwritten removing any custom changes.

I'm using version 10.0.1 with Umbraco 10.4.0

**Comment by enkelmedia** [comment]
Hi!

I understand. Due to changes in the way .NET Core include files from NuGet packages we have to copy in the files from the NuGet-package folder each time you build. There is a movement towards `Razor Class Libraries" but I have not had the time to update this package. So there is really no way around this, the files shipped with the package will always be overritten.

However, you can easily work around this by creating your own folder in App_Plugins and put your custom translations in this file eg.. `App_Plugins/MySite/Lang`. This way they wont be affected by our build step.

**Comment by huwred** [comment]
> However, you can easily work around this by creating your own folder in App_Plugins and put your custom translations in this file eg.. App_Plugins/MySite/Lang. This way they wont be affected by our build step.

Thanks for confirming, that is what I figured out I needed to do :)
